close all;clear all;

%Reading and plotting the input audio file which consists of a dialogie and a background
%music.
[data,fs] = audioread('dialogue.aac');
figure(1);
plot(data);

%Taking the FFT of the obtained matrix and then plotting it
res = fft(data);
%display(size(data));
figure(2);
plot(abs(res));

%Applying zero padding to the signal
res_z = fft(data, 100000);
figure(3);
plot(abs(res_z));

%Now, from the obtained I tried removing the background music from the main
%audio file by Low Pass, High Pass, and band Pass filers. I found out that
%High pass and Band Pass did the needful. Hence,below is the implementation
%of them.

%Using High Pass
hp=highpass(data,2200,fs);
fft_of_hp = fft(hp);
figure(4);
plot(abs(fft_of_hp));

%Using Band Pass
bp=bandpass(data,[1500 3000],fs);
fft_of_bp = fft(bp);
figure(5);
plot(abs(fft_of_bp));

%Audio files generated after implementing filters
audiowrite('dailogue_hp.ogg', hp, fs);  %Generated by High Pass
audiowrite('dialogue_bp.ogg', bp, fs);  %Generated by Band Pass



 